publish_mode: editorial_workflow

backend:
  name: git-gateway
  #  repo: avra-me/avra-me.github.io
  commit_messages:
    create: '[skip ci] Create {{collection}} “{{slug}}”'
    update: '[skip ci] Update {{collection}} “{{slug}}”'
    delete: '[skip ci] Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: public/assets
public_folder: /assets
format: yaml

local_backend: true

colorWidget: &color
  widget: string
  pattern: ['#[0-9]{6}', 'Must be a Hex Colour Value']

collections:
  - name: "common"
    label: "App Configuration"
    files:
      - label: Site Theme
        name: theme
        file: 'content/theme/theme.json'
        description: Configure your site
        fields:
          - label: "Colours"
            name: palette
            widget: object
            fields:
              - label: Primary Color
                name: primary
                widget: object
                fields: [ { *color, name: light, required: false },{ *color, name: main },{ *color, name: dark, required: false } ]
              - label: Secondary Color
                name: secondary
                widget: object
                fields: [ { *color, name: light, required: false },{ *color, name: main },{ *color, name: dark, required: false } ]
              - label: Tonal Offset
                name: tonalOffset
                widget: number
                min: 0
                max: 1
                valueType: float
              - label: Spacing
                name: spacing
                widget: number
                step: 4
              - label: "Default Mode"
                name: "type"
                widget: select
                options: [ "light", "dark" ]
      - label: Navigation
        name: navigation
        file: 'content/common/navigation/config.yaml'
        description: Configure your site
        fields:
          - { label: Disabled, default: false, name: disabled, widget: boolean, hint: This will enable/disable the header banner }
          - { label: Show Icon for static menus, default: false, name: staticIconEnabled, widget: boolean, hint: This effect will not be seen in preview }
      - label: Footer
        description: "Customize the footer"
        name: footer
        file: 'content/common/footer/config.yaml'
        fields:
          - { label: Disabled, default: false, name: disabled, widget: boolean, hint: This will enable/disable the footer }
          - { label: Footer Header, name: header, widget: string, hint: "A short, snappy tag line" }
          - { label: Footer SubText, name: caption, widget: text, hint: "A short, snappy tag line" }
  - label: "Navigation Buttons"
    name: navigation_buttons
    folder: content/common/navigation
    slug: "{{title}}"
    fields:
      - { name: "title", label: Name, widget: string, hint: "This will be the button label" }
      - { name: "icon", label: Icon, widget: string, hint: "This will be the icon displayed for mobile navigation" }
      - { name: "type", widget: hidden, default: "navigation" }
      - { name: "link", label: Link, widget: string, hint: "This will be where the button takes you" }
      - { name: "order", label: order, widget: number, hint: "Lowest number is first" }
  - name: footer_buttons
    label: "Footer Buttons"
    folder: content/common/footer
    create: true
    slug: "{{label}}_{{type}}"
    fields:
      - {label: "Body", name: "body", widget: "markdown"}
      - { name: "type", label: Button Type, widget: select, options: [ { label: "Attribution buttons", value: "attr" }, { label: "Social Media links", value: "social" } ] }
      - { name: "icon", label: Icon, widget: image }
      - { name: "link", lsabel: Link, widget: string, hint: "This will be where the button takes you" }
  - name: education_cards
    label: "Education (items)"
    folder: content/education/cards
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "type", widget: hidden, default: "GenericItem" }
      - { label: "Featured Image", name: "image", widget: image }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "SubTitle", name: "subTitle", widget: "string" }
      - { label: "Start Date", name: "startDate", widget: "datetime" }
      - { label: "End Date", name: "endDate", widget: "datetime", required: false }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Short Description", name: "short", widget: "text", required: false}
      - { label: "Body", name: "body", widget: "markdown" }
  - name: experience_cards
    label: "Experience (items)"
    folder: content/experience/cards
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "type", widget: hidden, default: "GenericItem" }
      - { label: "Featured Image", name: "image", widget: image }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "SubTitle", name: "subTitle", widget: "string" }
      - { label: "Start Date", name: "startDate", widget: "datetime" }
      - { label: "End Date", name: "endDate", widget: "datetime", required: false }
      - { label: "Tags", name: "summaryCards", widget: "list" }
      - { label: "Short Description", name: "short", widget: "text", required: false}
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Link", name: "link", widget: "string", required: false }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
